### ISSUE TITLE
Create Modal: increase spacing between form items to 32px

### ISSUE THREAD

**Issue by sydrosa** [carbon-design-system/ibm-cloud-cognitive#943] opened 2021-06-24 14:50 UTC
Per [this issue ](https://github.com/carbon-design-system/carbon/issues/8680)in Carbon, currently having an invalid state on a form field inside of the modal will push the modals height, since the invalid form text adds an additional 16px of padding.

After discussing with Andrew and Lauren Rice, we've decided to increase the spacing between form items to 32px to ensure that the invalid form text has room to display without pushing the height of the modal.

**Comment by lee-chase** [comment] 2021-11-01 17:19
@sydrosa what is the status of this issue?

**Comment by davidmenendez** [comment] 2021-11-30 20:02
i don't think there's anything we can do about this. adding margin or padding won't fix this issue. we'd have to add a static height to these inputs to ensure when the message appears that the height isn't changed, which isn't a good idea because there's no way to be sure what the height should be since it's dependent on the content. i think this issue has to be addressed by carbon.

thoughts, @sydrosa?

**Comment by lee-chase** [comment] 2022-03-04 12:23
This is an issue with the way Carbon has chosen to layout the TextInput, which they have described as working as designed. 

As we have commented in the Carbon issue, a user  who does not want the content to move when the invalid message appears could set the helperText to something that is not visible to the user e.g. &nbsp; which reserves the vertical space needed for the invalidMessage.

**Closed by lee-chase** 2022-03-04 12:23 UTC
Labels: type: bug
