### ISSUE TITLE
PageHeader's action bar icons don't render correctly

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/ibm-cloud-cognitive#682] opened 2021-04-29 14:55 UTC
<img width="378" alt="Screen Shot 2021-04-29 at 10 26 18 AM" src="https://user-images.githubusercontent.com/12755042/116567272-78049a00-a8d5-11eb-86e2-d410557407fb.png">

### How I am using the component

<img width="457" alt="Screen Shot 2021-04-29 at 10 56 02 AM" src="https://user-images.githubusercontent.com/12755042/116571908-805ed400-a8d9-11eb-9d5a-b06a4e5ccd33.png">

## What package(s) are you using?

- [x] Cloud & Cognitive
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

When using Filled icons from `@carbon/icons-react` inside the `actionBarItems` prop, it renders them differently. I think this has to do with some styling inside the action bar items. 
When I render them on the page regularly at that size the icons look as expected.

> Is this issue related to a specific component?
PageHeader

> What browser are you working in?

Google Chrome

> What version of the @carbon/ibm-cloud-cognitive package are you using?
`0.35.20`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Watson AI Ops

## Steps to reproduce the issue

1. Add a filled icon to the actionBarItems prop

## Codesandbox 
https://codesandbox.io/s/misty-forest-qgh9f?file=/src/index.js

**Comment by AlexanderMelox** [comment] 2021-04-29 14:57
## Example with other icons that are not filled 
<img width="341" alt="Screen Shot 2021-04-29 at 10 57 43 AM" src="https://user-images.githubusercontent.com/12755042/116572181-bbf99e00-a8d9-11eb-8143-4d21ed1cc7bb.png">

**Comment by lee-chase** [comment] 2021-05-25 12:07
@AlexanderMelox this appears to be an issue with Carbon Information icon. If the codesandbox ever loads, I ran it locally, the InformationFilled16 icon has an I that is filled black. This could be because the icon is out of date or because the CSS is incorrect. Please raise an issue with Carbon and close this.

```
import "./config";
import { PageHeader } from "@carbon/ibm-cloud-cognitive";
import React from "react";
import { render } from "react-dom";
import { InformationFilled16, NextFilled32 } from "@carbon/icons-react";
import {Button} from "carbon-components-react";

import "@carbon/ibm-cloud-cognitive/css/index.min.css";
import "carbon-components/css/carbon-components.min.css";

const App = () => (
  <>
    <PageHeader
      background
      title="Test"
      subtitle={<div>
        <InformationFilled16 />
        <NextFilled32 style={{width: '16px', height: '16px'}}/>
        <Button renderIcon={InformationFilled16} hasIconOnly kind="ghost" />
        <Button renderIcon={NextFilled32} hasIconOnly kind="ghost" />
        </div>}
      // breadcrumbItems={[]}
      actionBarItems={[
        {
          iconDescription: "hello",
          renderIcon: NextFilled32
        },
        {
          iconDescription: "hello",
          renderIcon: InformationFilled16
        }
      ]}
    />
    <div className="content" style={{ minHeight: "150vh" }}>
      Some content
      <InformationFilled16 /> <NextFilled32 style={{width: '16px', height: '16px'}}/>
        <Button renderIcon={InformationFilled16} hasIconOnly kind="ghost" />
        <Button renderIcon={NextFilled32} hasIconOnly kind="ghost" />

    </div>
  </>
);

render(<App />, document.getElementById("root"));
```

![image](https://user-images.githubusercontent.com/15086604/119495227-19a6cc00-bd5a-11eb-8323-8f8659861c61.png)


![image](https://user-images.githubusercontent.com/15086604/119494806-9c7b5700-bd59-11eb-8e5a-e32da5771282.png)

**Comment by andrea-gm** [comment] 2021-06-17 15:48
@AlexanderMelox we can't reproduce. closing. Lee recommends you raise a carbon issue.

**Closed by andrea-gm** 2021-06-17 15:48 UTC
Labels: type: bug
