### ISSUE TITLE
Modified tabs

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-cloud-cognitive#33] opened 2020-07-28 09:38 UTC
Modified Tabs design -> https://github.com/carbon-design-system/ibm-cloud-paks/issues/33
Designer ->

**Comment by carrenelloyd** [comment] 2020-07-30 18:26
[**Link to design**](https://pages.github.ibm.com/cdai-design/pal/components/modified-tabs/)

Maintainers: Marci Coral

Catalog number: 14

**Comment by SimonFinney** [comment] 2020-08-05 13:10
@carrenelloyd Would you know if there's redlines or existing code available for this?

**Comment by lee-chase** [comment] 2020-08-12 19:18
@SimonFinney I have done some initial exploration on an internal repo. Unsure where to put the code while https://pages.github.ibm.com/lee-chase/modified-tabs/

Not sure if I should dump what I have into the CDAI package

**Comment by lee-chase** [comment] 2020-08-12 19:37
@carrenelloyd The design page talks about "modified tabs" and "web terminal"

**Comment by lee-chase** [comment] 2020-08-12 20:10
@carrenelloyd  Design questions/thoughts

1. I am not certain the modified-tabs should provide an "Are you sure?" dialog. I believe the best model is to defer this to the consumer who can choose whether to display a dialog (which we can supply as a pattern) or not and manage the save process. If we do supply a dialog the user will need to supply content and a handler to process any save. From a technical point of view, a handler is required regardless.
2. Using the standard tabs as a base the close button requires us to undo some of the overflow (scroll, hide or spill out) put in by the carbon team to show the tooltip.
3. After clicking new tab what should have focus/be selected?
4. After clicking a close button what should happen to focus.
5. Carbon recommends choosing another pattern such as a side nav for more than 6. The design as written gives the impression Carbon recommends using an overflow.
6. No Invision prototype has been shared as far as I can tell.
7. Regardless of sorting Tab order is somewhat irrelevant, tabs are ordered by the data used to populate them. 
8. Are all tabs different versions of the same view? Or can they be different? If the latter what dictates the contents of a new tab?
9. How does a tab receive a name?

**Comment by SimonFinney** [comment] 2020-08-13 09:50
@lee-chase This looks and feels brilliant, and thanks for taking it on! It'd be great when you feel it's progressed enough, to submit a PR directly into this repo so the group could discuss and work out the details in review?

**Comment by lee-chase** [comment] 2020-08-13 10:18
Another question or two... 

10. When a tab is retrieved from the overflow is this what happens? Assuming placed in position 6, position 1 item placed in overflow in the order supplied by the consumer.

**Comment by lee-chase** [comment] 2020-08-13 10:20
@SimonFinney without a defined package for CD&AI the barrier to submitting a PR for single component seems quite high.

**Comment by lee-chase** [comment] 2020-08-15 11:44
@SimonFinney need to be able to tag the designer and or assign when we have questions.

**Comment by lee-chase** [comment] 2020-08-15 11:46
11. Is new really a tab or a button styled to look like one? Does it have content like a normal tab. Does it change after being clicked or selected?

NOTE: That it is possible to select a tab using cursor keys, is that to be considered a call to create a new tab? Tabs do not otherwise handle keyboard events. We should probably make this a ghost button.

**Comment by SimonFinney** [comment] 2020-08-16 14:07
Good point @lee-chase ! Were you able to connect with the maintaining designer on Slack? We'll need their public GitHub account to add it to @carbon-design-system/ibm-cloud-paks-design

**Comment by lee-chase** [comment] 2020-08-16 15:24
> Good point @lee-chase ! Were you able to connect with the maintaining designer on Slack? We'll need their public GitHub account to add it to @carbon-design-system/ibm-cloud-paks-design

I was unable to identify them on slack.

**Comment by lee-chase** [comment] 2020-09-14 12:59
@gatfora needs clarification from design otherwise will end up with my best guesses.

**Comment by lee-chase** [comment] 2020-09-14 14:17
13. The keyboard interaction of standard tabs is as follows. 
 - The user can tab to the selected item of the tab set.
 - When the tab set has focus the tab key moves focus away from the tab set.
 - Cursor keys are used to move between tabs

With a close button on each tab (except new) should focus move to the close button when a tab set is selected, with a subsequent key press moving the focus out of the tab set?

**Comment by lee-chase** [comment] 2020-09-15 12:17
Marcie can you update with the actual maintainer and ensure they are here and on github.com?

DESIGN CHANGE: Carbon has switched the narrow view to use right/left scroll arrows. This conflicts with the overflow menu solution.

![image](https://user-images.githubusercontent.com/15086604/93207982-bb016b00-f753-11ea-80ef-4485173453df.png)

**Comment by lee-chase** [comment] 2020-09-15 12:18
Also worth noting that Carbon has a bug with dynamic addition of tabs https://github.com/carbon-design-system/carbon/issues/6838

**Comment by marciecorral** [comment] 2020-09-15 15:08
This was designed for MCM about a year ago, but they never actually made it into the product. Our team is now focused on Project Katamari and nothing net new is going into CP4MCM. I think at this point, if there is a consistent need for this as a pattern, we will need to determine who could actually code it. This will be a topic on the DSAG call on Thursday. Our FED, Alex will be joining to help clarify some of the possible constraints, etc.

**Comment by lee-chase** [comment] 2020-09-15 17:05
14. On closing a tab - typically the choice to save content is three way - Save, Do not save, Cancel. Is a three option modal dialog required as Carbon does not support this?

**Comment by lee-chase** [comment] 2020-09-15 17:56
15. Does a tab need to indicate it is dirty (in need of saving)

**Comment by lee-chase** [comment] 2020-09-16 16:04
No further work possible here without a review.

**Comment by andrea-gm** [comment] 2021-02-17 02:20
@lee-chase I'm trying to understand the status here. Are you in need of a design review? Or is the pattern itself incomplete?

**Comment by lee-chase** [comment] 2021-02-24 18:06
@andrea-gm A start was made. There are a number of open design questions. Carbon has made styling changes that break it since it was created.

**Comment by Levinson1** [comment] 2021-02-24 18:27
@marciecorral can you or someone that helped document the original pattern help answer the questions Lee asked so we can get this one completed. Thanks.

**Closed** 2022-04-27 21:25 UTC
Labels: status: wontfix, needs: ux, status: blocked, Epic
