### ISSUE TITLE
pageHeader action button size not getting adjusted according to text provided

### ISSUE THREAD

**Issue by Nishi-Chandra1** [carbon-design-system/ibm-cloud-cognitive#1468] opened 2021-11-22 04:40 UTC
i am trying to use PageHeader component with pageAction props . When i am trying to give more text inside primary/secondary button, the button size is not getting adjusted automatically, rather the content of button is going out. Seems like some fixed width is given for each action buttons
<img width="1031" alt="Screenshot 2021-11-16 at 4 16 19 PM" src="https://user-images.githubusercontent.com/80027651/142802150-9d230a52-6493-4593-a5ff-7427b4ea7ce9.png">
. 

This issue was also discussed here: https://ibm-casdesign.slack.com/archives/C013ZTX0N6B/p1637060158138500

**Comment by lee-chase** [comment] 2021-11-22 12:12
@Nishi-Chandra1 the width of the button is restricted by it being in a button set, due to Carbon styling which we would not want to override. 

It may be possible for us to modify the page actions to use an ordinary button when only one is supplied. A recent change to make the page action area more flexible allows you to supply this instead. 

```jsx
const pageActions = {
  content: (
    <div style={{ display: "flex", justifyContent: "flex-end" }}>
      <Button kind="primary">Configure Risk Profile Options</Button>
    </div>
  ),
  minWidth: "180px",
  maxWidth: "100%"
};
```

**Comment by Nishi-Chandra1** [comment] 2021-11-22 12:31
If this behaves same as primary/secondary button on pageHeader, then its fine to go ahead.
the position should still be sticky once page is scrolled and aligned with breadcrumbs

**Comment by lee-chase** [comment] 2021-11-22 12:47
@Nishi-Chandra1 it is still sticky, see 

https://codesandbox.io/s/gallant-worker-m3483?file=/src/components/SamplePage/SamplePage.js:776-1004

**Comment by Nishi-Chandra1** [comment] 2021-11-22 13:08
This looks fine. but why one more button is hidden backside of Configure risk profile options button??
<img width="720" alt="Screenshot 2021-11-22 at 6 37 49 PM" src="https://user-images.githubusercontent.com/80027651/142867228-0a55d6f7-a1b7-470a-9732-5f5748185d76.png">

**Comment by dcwarwick** [comment] 2021-11-22 15:17
@Nishi-Chandra1 Good spot: because of the long text in the button, this button is making itself too large for the available area, which by design is clipped to 40% of the page header width. That's leading to some unpleasant overlap effects!
- Adding `max-width: 100%` to the button will ensure that the button does not expand beyond its available space. I've made that change in the codesandbox that Lee shared, and that resolves the visual issue:
![image](https://user-images.githubusercontent.com/6385315/142886742-426eb847-2e18-45c2-add8-cc61e1fb44a6.png)
- Also, @lee-chase, I think the action area container DIV should have `overflow: hidden`, so that if user-provided content _does_ spill out of the available space it doesn't overlay (or underlay) the other parts of the page header as it did here.

**Comment by lee-chase** [comment] 2021-11-22 19:39
@dcwarwick #1470 addresses the styling glitch, should probably raise an enhancement request to render a button only for a single item. Perhaps a PR to Carbon.

**Comment by lee-chase** [comment] 2021-11-24 13:47
@Nishi-Chandra1 with #1470 merged I believe this to be resolved. You can either supply your own button or a single pageAction

**Closed by lee-chase** 2021-11-24 13:47 UTC
Labels: type: bug
